import type { UsageResponse } from "./types";
const fixtureRate = {
  rateVersion: "illustrative-1",
  source: "https://example.test/synthetic-rates",
  observedAt: "2026-09-24T00:00:00Z",
  effectiveAt: "2026-09-24T00:00:00Z",
  validUntil: "2026-10-24T00:00:00Z",
  pinnedAt: "2026-09-24T01:00:00Z",
  serviceTier: "standard",
};
// Illustrative only: synthetic charges, no provider pricing or verification evidence.
export const usageFixture: UsageResponse = {
  version: 1,
  projectId: 1,
  isExample: true,
  range: "all",
  offset: 0,
  limit: 100,
  total: 2,
  totals: {
    completeCost: "0.0012",
    partialCost: "0.0003",
    completeRuns: 1,
    partialRuns: 1,
    unavailableRuns: 0,
    legacyRuns: 0,
    reportedRuns: 2,
  },
  feedback: { accepted: 1, rejected: 0, rated: 1, total: 3 },
  limitations: [
    "Estimates cover reported runs only, not the provider account or invoice.",
  ],
  runs: [
    {
      id: 1,
      jenkinsBuildId: "report-12",
      createdAt: "2026-09-24T12:00:00Z",
      model: "fixture-model",
      provider: "openai",
      runtimeId: 1,
      runtimeVersion: "fixture",
      deploymentId: 1,
      executionRevisionId: 12,
      task: "other",
      mode: "single_call",
      gate: "pass",
      gateReason: null,
      usageStatus: "complete",
      billing: {
        version: 1,
        basis: "native",
        status: "complete",
        knownCost: "0.0012",
        currency: "USD",
        reasons: [],
        categories: [
          {
            category: "input",
            tokens: 100,
            ratePerMillion: "2",
            cost: "0.0002",
          },
          {
            category: "output",
            tokens: 20,
            ratePerMillion: "50",
            cost: "0.001",
          },
          {
            category: "cache_read",
            tokens: 0,
            ratePerMillion: null,
            cost: "0",
          },
        ],
        rateSnapshot: fixtureRate,
      },
      legacyCost: null,
      usage: {
        inputTokens: 100,
        outputTokens: 20,
        cacheReadTokens: 0,
        serviceTier: "standard",
        reportedModelId: "fixture-model",
      },
      legacyUsage: null,
      feedback: { accepted: 0, rejected: 0, rated: 0, total: 0 },
      taskResult: {
        kind: "report",
        executionStatus: "completed",
        validationStatus: "not_run",
        baseCommit: null,
        report: {
          summary: "Synthetic release summary",
          uncertainty: null,
          nextSteps: [],
          evidenceArtifactIds: [],
        },
        patch: null,
        artifacts: [],
        validations: [],
      },
    },
    {
      id: 2,
      jenkinsBuildId: "aborted-13",
      createdAt: "2026-09-24T13:00:00Z",
      model: "fixture-model-2",
      provider: "google",
      runtimeId: 2,
      runtimeVersion: "fixture",
      deploymentId: 2,
      executionRevisionId: 13,
      task: "security_analysis",
      mode: "opencode",
      gate: "fail",
      gateReason: "Time limit",
      usageStatus: "partial",
      billing: {
        version: 1,
        basis: "opencode_normalized",
        status: "partial",
        knownCost: "0.0003",
        currency: "USD",
        reasons: ["runner_billing_incomplete"],
        categories: [
          {
            category: "input",
            tokens: 100,
            ratePerMillion: "3",
            cost: "0.0003",
          },
        ],
        rateSnapshot: { ...fixtureRate, serviceTier: "all" },
      },
      legacyCost: null,
      usage: { inputTokens: 100, outputTokens: null },
      legacyUsage: null,
      feedback: { accepted: 1, rejected: 0, rated: 1, total: 3 },
      taskResult: {
        kind: "findings",
        executionStatus: "timed_out",
        executionReason: "Time limit",
        validationStatus: "not_run",
        baseCommit: null,
        report: null,
        patch: null,
        artifacts: [],
        validations: [],
      },
    },
  ],
};
