import type { Benchmark, Observation, Page, ModelDetail } from "./types";
export const page = <T>(
  items: T[],
  nextCursor: string | null = null,
): Page<T> => ({
  items,
  pageInfo: { limit: 25, hasMore: !!nextCursor, nextCursor },
});
export const benchmark: Benchmark = {
  id: 1,
  slug: "gpqa-diamond",
  name: "GPQA Diamond",
  description: null,
  tooltip:
    "Difficult graduate-level science questions; measures answer accuracy, not code-review ability.",
  methodologyUrl: "https://example.org/method",
  limitations: "Compare matching settings.",
  collection: "reasoning_knowledge",
  sources: [],
  versionLabels: ["Diamond"],
  metricUnits: ["percent"],
};
export const model: ModelDetail = {
  id: 1,
  slug: "alpha",
  name: "Alpha 1",
  organization: "Example Lab",
  description: null,
  aliases: ["alpha-v1"],
  deployments: [],
};
export const observation: Observation = {
  id: 1,
  benchmarkId: 1,
  benchmarkName: benchmark.name,
  versionId: 1,
  version: "Diamond",
  protocolId: 1,
  protocol: "five-shot",
  evaluatorId: 1,
  evaluator: "Authors",
  sourceSnapshotId: 1,
  sourceName: "Author report",
  sourceUrl: "urn:sha256:123",
  sourceContentHash: "a".repeat(64),
  sourceFetchedAt: "2026-09-24T00:00:00Z",
  sourcePublicationDate: null,
  snapshotStatus: "active",
  citationUrl: "https://example.org/report",
  coverageNote: "Three reviewed models.",
  runner: "Official runner",
  runnerVersion: null,
  protocolConfiguration: { effort: "high" },
  sourceModelLabel: "alpha-v1",
  modelId: 1,
  modelName: "Alpha 1",
  providerId: null,
  providerName: null,
  origin: "source",
  provenanceStatus: "complete",
  contextWindow: null,
  observedAt: null,
  metrics: [
    {
      metricId: 1,
      key: "accuracy",
      name: "Accuracy",
      description: "Correct answers.",
      unit: "percent",
      direction: "higher",
      value: "91.25",
      reportedValue: "91.25",
      missingReason: null,
      category: null,
      subset: null,
      aggregation: null,
      confidenceLow: null,
      confidenceHigh: null,
      confidenceLevel: null,
      uncertaintyType: null,
      sampleSize: 500,
      denominator: 500,
      attempts: 1,
    },
  ],
};
